### PR TITLE
feat(eslint-comments): aid maintainability of eslint directives

### PR DESCRIPTION
**Pull request by PixnBits**
[eslint-plugin-eslint-comments](https://www.npmjs.com/package/eslint-plugin-eslint-comments)
BREAKING CHANGE: [7 new rules](https://github.com/mysticatea/eslint-plugin-eslint-comments/tree/master/docs/rules) added as errors

## Description

Please make sure that the PR fulfills these requirements

- [x] I checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] Rule changes includes a comment to describe the reasoning behind the change.
- [ ] PR contains a single rule change.
    
## Motivation and Context

Usually eslint directives are overrides of a preset or project-level configuration. There are situations where an override may be the best path. This plugin helps those instances to be applied to the right location, record the reasoning behind the override, prevent unintended side-effects (ex: applying to more locations by forgetting to re-enable the rule), and remove unused rule violation overrides.

Most visible to developers will be [eslint-comments/require-description](https://github.com/mysticatea/eslint-plugin-eslint-comments/blob/master/docs/rules/require-description.md). This uses the [description-in-directive-comments RFC](https://github.com/eslint/rfcs/blob/master/designs/2019-description-in-directive-comments/README.md) to require a description on the eslint directive. Practically, this means instead of
```javascript
// description on why this exception is seen as appropriate
// eslint-disable-next-line global-require
const fizz = require(buzz);
```
developers can use
```javascript
// eslint-disable-next-line global-require -- description on why this exception is seen as appropriate
const fizz = require(buzz);
```
This formalization also enables other tooling in the future, ex: generating a list of reasons preset overrides are used in a project (many uses, notably assessing if a certain rule is becoming troublesome). 

Other rules from the plugin but not enabled by this PR are [`eslint-comments/no-use`](https://github.com/mysticatea/eslint-plugin-eslint-comments/blob/master/docs/rules/no-use.md) and [`eslint-comments/no-restricted-disable`](https://github.com/mysticatea/eslint-plugin-eslint-comments/blob/master/docs/rules/no-restricted-disable.md). These would be tricky to configure well for multiple projects and would probably encourage developers to disable the preset entirely.

## How Has This Been Tested?

I've `$ npm pack`'d and `$ npm install`'d this change in another project and saw the only changes needed were to remove unused directives and editing the other directives to move the comments to the formal format.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update

If these rules are desirable in this preset I can open another PR to also add them as warnings for usage in the current major version.

### CODE REVIEW

**Review by marcusrbrown — DISMISSED** [review]

**Comment by JAdshead** [comment]
a little confused, does this require descriptions be on the same line as the override ? if so is this going to cause conflicts with line length ?

**Comment by marcusrbrown** [comment]
> a little confused, does this require descriptions be on the same line as the override or makes it optional ? if so is this going to cause conflicts with line length ?

It requires descriptions on the same line. @PixnBits brought this conflict up in eslint/eslint#14284 and it looks like they are ok with supporting multiple line descriptions.

**Review by nellyk — DISMISSED** [review]

**Comment by nellyk** [comment]
Thank you for raising this changes, it is definitely going to improve my developer experience

**Comment by marcusrbrown** [comment]
I want to make sure that you're good @JAdshead. Ok to merge?

**Review by infoxicator — DISMISSED** [review]

**Comment by JAdshead** [comment]
hmm description-in-directive-comments RFC does say "ESLint ignores the part preceded by \s-{2,}\s in directive comments." which i could mean that rules such as max-len are not applied

```
"Longer is OK."
// eslint-disable-line -------- this part is ignored.
```

**Review by 10xLaCroixDrinker — APPROVED** [review]

**Review by JAdshead — APPROVED** [review]

**Pull request merged**
