### PR TITLE
Feat/typescript support

### PR DESCRIPTION
**Pull request by markbello**
## Description

Please make sure that the PR fulfills these requirements

- [x] I checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] Rule changes includes a comment to describe the reasoning behind the change.
- [ ] PR contains a single rule change.
    
## Motivation and Context

The config needs some tweaks in order to support Typescript

## How Has This Been Tested?

Deployed a local copy of the config into a mixed js/jsx/ts/tsx repo to confirm none of the rules broke

Confirmed that TS files were picking up linter rules and that JS files wouldn't break

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update

### CODE REVIEW

**Comment by smackfu** [comment]
@markbello can you fix the conflicts and remove the extra commits?

**Review by JAdshead — CHANGES_REQUESTED** [review]
TS should probably be its own config

**Comment by markbello** [comment]
> TS should probably be its own config

so put my changes in like a `typescript.js` or something?

**Comment by nellyk** [comment]
@markbello  Thank you for contributions, could you please resolve the conflict and update the PR as requested. Let us know if you have any questions

**Comment by JAdshead** [comment]
closing due to lack of activity

**Pull request closed without merging**
