### PR TITLE
feat(eslint): prefer stateless functional components

### PR DESCRIPTION
**Pull request by stevensacks**

### CODE REVIEW

**Comment by smackfu** [comment]
v10 already has this enabled, was it disabled in v12?:
```
    "react/prefer-stateless-function": [
      "error",
      {
        "ignorePureComponents": true
      }
    ],
```

**Comment by stevensacks** [comment]
If that's the case, then we don't need this.

**Comment by PixnBits** [comment]
@smackfu do you know where that was configured? I'm not seeing it in the repo now, but also not seeing a PR that would have removed it. I'm guessing I'm missing the end of my nose though, but also don't want to decline this PR if the rule was indeed removed. 🙏

**Comment by smackfu** [comment]
> @smackfu do you know where that was configured? I'm not seeing it in the repo now, but also not seeing a PR that would have removed it. I'm guessing I'm missing the end of my nose though, but also don't want to decline this PR if the rule was indeed removed. 🙏

Here's where it is defined in airbnb:
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js#L217

**Comment by PixnBits** [comment]
Thanks, @smackfu, that's the sort of thing I figured I was missing 😅.
Rather than declining the PR, it might be good to add a test that checks that the rule, as exported by this package, is set? Might be good as a separate PR too 🤙but don't want to lose track of the root suggestion

**Comment by stevensacks** [comment]
Redundant.

**Pull request closed without merging**
